[package]
name = "engine"
version = "0.1.0"
authors = ["Samuel Casavant <samuel.j.casavant@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = { version = "1.0", optional = true }
bevy = { version = "0.5.0" } # , features = ["dynamic"] }
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap.git", features = ["tiled_map"] }
indexmap = "1.7.0"
log = "0.4"
morton-encoding = "2.0"
pathfinding = "2.0.4"
pretty_trace = {git = "https://github.com/10XGenomics/rust-toolbox.git"}
rand = "0.8.4"
serde_json = { version = "1.0", optional = true }
tiled = { version = "0.9", default-features = false, optional = true }

[profile.release]
debug = true
lto = "thin"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[workspace.metadata.dylint]
libraries = [
  { git = "https://github.com/MinerSebas/bevy_lint", branch = "main" },
]
