[package]
name = "game"
version = "0.1.0"
authors = ["Samuel Casavant <samuel.j.casavant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
rand = "0.7.3"
pathfinding = "2.0.4"
bevy_tiled = { git = "https://github.com/StarArawn/bevy_tiled.git"}